export const MIN_DELIVERY_PRICE_WHOLESALE = 5000;
export const DELIVERY_PRICE_WHOLESALE = 1000;
export const FREE_DELIVERY_RATE_WHOLESALE = 10000;

export const MIN_DELIVERY_PRICE_RETAIL = 2000;
export const DELIVERY_PRICE_RETAIL = 0;
export const FREE_DELIVERY_RATE_RETAIL = 2000;
