# Generated by Django 3.0.8 on 2020-08-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200731_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фото продукта'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информация о продукте'},
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='text',
            new_name='value',
        ),
    ]
