# Generated by Django 3.0.8 on 2020-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200804_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_translit',
            field=models.CharField(default='example', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='translit_name',
            field=models.CharField(default='example', max_length=256),
            preserve_default=False,
        ),
    ]
