# Generated by Django 3.0.8 on 2020-08-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200810_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='translit_name',
            new_name='name_translit',
        ),
    ]
