# Generated by Django 3.0.8 on 2020-08-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200810_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('address', models.CharField(max_length=512, verbose_name='Email')),
                ('comment', models.CharField(max_length=512, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name_translit',
            field=models.CharField(max_length=256, verbose_name='Название в ссылке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_translit',
            field=models.CharField(max_length=256, verbose_name='Название в ссылке'),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product')),
            ],
        ),
    ]
