# Generated by Django 3.0.8 on 2020-08-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200812_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
