# Generated by Django 3.0.8 on 2020-08-12 13:50

from django.db import migrations, models
import helpers.random_hash


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200812_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hash',
            field=models.CharField(default=helpers.random_hash.hash_string, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='hash_digital',
            field=models.CharField(default=helpers.random_hash.hash_digital, max_length=64),
        ),
    ]
