# Generated by Django 3.0.8 on 2020-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200812_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
