# Generated by Django 3.0.8 on 2020-08-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200814_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=64, verbose_name='Вес (объём)'),
        ),
    ]
