# Generated by Django 3.0.8 on 2020-09-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200820_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.CreateModel(
            name='ProductWeight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=64, verbose_name='Вес (объём)')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
            options={
                'verbose_name': 'Вес продукта',
                'verbose_name_plural': 'Вес продуктов',
            },
        ),
    ]
