# Generated by Django 3.0.8 on 2020-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200911_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweight',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
