# Generated by Django 3.0.8 on 2020-10-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_productweight_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweight',
            name='retail',
            field=models.BooleanField(default=False, verbose_name='Розница'),
        ),
        migrations.AlterField(
            model_name='productweight',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
