# Generated by Django 3.1.7 on 2021-03-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_retail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retail_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='retail_product', to='app.productweight')),
                ('wholesale_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wholesale_product', to='app.productweight')),
            ],
        ),
    ]
