# Generated by Django 3.1.7 on 2021-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210327_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductweight',
            name='retail_product',
            field=models.ManyToManyField(related_name='retail_product', to='app.ProductWeight', verbose_name='Розничный продукт'),
        ),
        migrations.AlterField(
            model_name='dailyproductweight',
            name='wholesale_product',
            field=models.ManyToManyField(related_name='wholesale_product', to='app.ProductWeight', verbose_name='Отповый продукт'),
        ),
    ]
