# Generated by Django 3.1.7 on 2021-03-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210327_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweight',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена (для скидок)'),
        ),
    ]
